server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/blog
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update        # 初回：create / 本番：none
    show-sql: true            # SQLログを表示
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  thymeleaf:
    cache: false              # 開発時キャッシュオフ
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

logging:
  level:
    root: info
    org.springframework.web: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
